# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Python hooks
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ["--ignore=E501"]
        language_version: python3
        additional_dependencies:
          - flake8-eradicate==1.3.0
  # C++ hooks
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [ --style=Google ]
      - id: cpplint
      - id: include-what-you-use
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: requirements-txt-fixer
